# Generated by Django 4.1.4 on 2022-12-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=False, verbose_name='Слать оповещения o новых комментариях?'),
        ),
    ]
